version: '3.7'
services:
  cms:
    build:
      context: ./cms/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
#    networks:
#      - default
    volumes:
      - ./cms:/var/www
    command: 'php -S 0.0.0.0:5000 -t /var/www/public'
  admin:
    build:
      context: ./admin/
      dockerfile: Dockerfile
#    networks:
#      - default
    volumes:
      - ./admin:/var/www
    command: 'npm run dev'
  nginx:
    restart: 'no'