version: "3.7"
services:
  cms:
    restart: always
    build:
      context: ./cms/
      dockerfile: Dockerfile.production
    #    networks:
    #      - backend
    env_file:
      - ./cms/.env
    depends_on:
      - memcached
      - redis
    command: "php-fpm"
  admin:
    restart: always
    build:
      context: ./admin/
      dockerfile: Dockerfile.production
    #    networks:
    #      - frontend
    ports:
      - 4000:4000
    env_file:
      - ./admin/.env
    depends_on:
      - cms
      - nginx
    command: "npm run start"
  nginx:
    image: "nginx:1.19"
    restart: always
    #    networks:
    #      - backend
    #      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cms:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
  mysql:
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/bitnami/mariadb/data
    env_file:
      - ./mysql/.env
  memcached:
    image: "docker.io/bitnami/memcached:1-debian-10"
    restart: always
    #    networks:
    #      - backend
    ports:
      - 11211:11211
  redis:
    image: "redis:alpine"
    restart: always
    #    networks:
    #      - backend
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./redis/.env
    command: "redis-server"
volumes:
  db:
    driver: local
#networks:
#  backend:
#    driver: bridge
#  frontend:
#    driver: bridge
